// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpWehFnuceLtjwFj2ZtbX5MJ-k2I1x2YA',
    appId: '1:738742699760:web:f1ce412deab480f3cfa435',
    messagingSenderId: '738742699760',
    projectId: 'question-app-edb4a',
    authDomain: 'question-app-edb4a.firebaseapp.com',
    storageBucket: 'question-app-edb4a.appspot.com',
    measurementId: 'G-P1ZPTMWTXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWnNM9Qd6emu_9aaBIcM1Y6FdEUklu1ts',
    appId: '1:738742699760:android:3ec1cd78d5734cc9cfa435',
    messagingSenderId: '738742699760',
    projectId: 'question-app-edb4a',
    storageBucket: 'question-app-edb4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjjUzJ0xKNmT1PSPxJolyMLd_cqtbyg7Y',
    appId: '1:738742699760:ios:541c64d9b306af7bcfa435',
    messagingSenderId: '738742699760',
    projectId: 'question-app-edb4a',
    storageBucket: 'question-app-edb4a.appspot.com',
    iosClientId: '738742699760-ig8f9485otfcvt4j17c6omf5tnr6mood.apps.googleusercontent.com',
    iosBundleId: 'com.questionapp.app',
  );
}
